apiVersion: v1
kind: Pod
metadata:
  name: "{{BOT_ID}}"
spec:
  containers:
    - name: "{{BOT_ID}}"
      image: "{{IMAGE_PATH}}"
      imagePullPolicy: "{{IMAGE_PULL_POLICY}}"
      command: [ "python", "bot.py", "{{BOT_ID}}" ]
      volumeMounts:
        - name: "manifest"
          mountPath: "/marsbots/{{BOT_ID}}"
        - name: "cog-character"
          mountPath: "/marsbots/{{BOT_ID}}/cogs"
      terminationMessagePath: "/tmp/{{BOT_ID}}.log"
      env:
        - name: DISCORD_TOKEN
          value: "{{DISCORD_TOKEN}}"
        - name: OPENAI_API_KEY
          value: "{{OPENAI_API_KEY}}"
        - name: MONGODB_URI
          value: "{{MONGODB_URI}}"
        - name: REDIS_URI
          value: "{{REDIS_URI}}"
      resources:
        limits:
          cpu: "200m"
          memory: "200Mi"
  volumes:
    - name: "manifest"
      configMap:
        name: "{{BOT_ID}}-manifest"
        items:
          - key: "manifest.yml"
            path: "manifest.yml"
    - name: "cog-character"
      configMap:
        name: "cog-character"
        items:
          - key: "character.py"
            path: "cogs/character.py"
  restartPolicy: Never
